- name: ensure PhpXdebug installed
  apt:
    pkg: php-xdebug
    state: present

- name: install PhpXdebug for php 7.1
  template:
    src: xdebug.ini.j2
    dest: /etc/php/7.1/mods-available/xdebug.ini
    force: yes
    mode: 0644