- name: ensure PHP installed
  apt: pkg={{ item }} state=latest
  with_items:
    - php5
    - php5-fpm
    - php5-dev
    - php5-cli
    - php5-pgsql
    - php5-mysql
    - php5-curl
    - php5-gd

- name: configure PHP-FPM settings
  template: src=fpm_php.ini.j2 dest=/etc/php5/fpm/php.ini
